
project_id = "wrnscwadcetbimpstnpu"

[functions.handle-email-webhook]
verify_jwt = false

[functions.revoke-user-session]
verify_jwt = false

[functions.confirm-user-email]
verify_jwt = false

[functions.parse-job-overview]
verify_jwt = false
