// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrnscwadcetbimpstnpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndybnNjd2FkY2V0YmltcHN0bnB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNzg5MDksImV4cCI6MjA2NDc1NDkwOX0.zWkFNauyxZ7t8omUVH7o7oarg8NTV35PXKp3xe7gx_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);